# lucidlint: ignore-file positional-literals the catalog rows are one uniform schema — kind, severity,
# group, languages, description in registration order; keyword-izing 60 rows would bury the data
"""Canonical rule metadata — the ONE registration point for every finding
family.

A rule is declared once, as a `Rule` in `CATALOG`. Everything the tool
needs is DERIVED from it:

- RULES.md tables — generated by `scripts/gen-rules.py` (`make rules`);
- `scanner/src/rules_gen.rs` — the Rust core's FAMILY_KINDS, STANDARD_KINDS,
  FAMILY_VARIANTS, `final_kind`, `rule_groups` — generated by the same step;
- `lucidlint.RULE_GROUPS` — the catalog's config groups (the gate's
  `group:` config expansion);
- suppression family matching (FAMILY_VARIANTS) — the catalog's `display`
  buckets (`ignore latent-class <why>` covers closures/partition/strewing
  because all three declare display="latent-class" here).

The drift gate (`make rules --check`, pinned by the pytest suite) fails when
the generated artifacts or the scanner's emissions disagree with this file —
a rule added here but never emitted, or emitted but never registered, cannot
silently ship. There is no second registration point to forget.
"""

from dataclasses import dataclass

# RULES.md display groups in order — (name, header suffix, intro note)
GROUP_INFO = {
    "architecture": (
        "Group 1: Architecture & design",
        "&dagger; *More likely to conflict with existing conventions. The "
        "threshold values (15 CC, 120 lines, 5 fields, 0.9 dice) are "
        "opinionated — adjust by suppressing specific findings with a why.*",
    ),
    "style": ("Group 2: Style & correctness", None),
    "test-discipline": ("Group 3: Test discipline", None),
    "suppression": ("Group 4: Suppression discipline", None),
    "advice": (
        "Group 4.5: Refactoring advice",
        "&dagger; *(all warn — detection-only) These detect the code SHAPE a "
        "Fowler refactoring targets. The fix is named in the message for the "
        "agent to hand-apply (auto-fixes exist for magic-number, vague-name, "
        "and long-param-list; see the fix engine).*",
    ),
    "graph": (
        "Group 5: Hotspot & risk (graph-based)",
        "These rules require the optional `code-review-graph` tool (installed "
        "separately or via `pip install code-review-graph`). Without it they "
        "degrade silently.",
    ),
    "cross-cutting": ("Group 6: Cross-cutting", None),
}


@dataclass(frozen=True)
class Rule:
    """One finding family: the kind (signal) plus every piece of metadata
    the tool needs, so a rule is registered exactly once.

    - `kind` — the raw signal suppressions match on (`lucidlint: ignore
      <kind>`, config `ignore = ["<kind>"]`, baseline identity).
    - `severity` — `fail` (blocks the gate) or `warn` (reported only).
    - `display_group` — the RULES.md section the rule's row lives in.
    - `languages` — the RULES.md language column (Both/Python/Rust/Graph).
    - `description` — the RULES.md row text; the message's fix directive is
      separate (the scanner owns it).
    - `display_name` — the RULES.md row title when it differs from the kind
      (e.g. `closures → latent-class`).
    - `display` — the final_kind display bucket: `None` → the kind is its
      own bucket; `"standard"` → collapses to the catch-all (the message
      carries the rule); any other value → a FAMILY, and every rule sharing
      that value is a variant of it (FAMILY_VARIANTS is derived from here —
      the review-log B6 lesson: a variant missing from the alias map makes
      `ignore <family> <why>` silently stale).
    """

    kind: str
    severity: str
    display_group: str
    languages: str
    description: str
    display_name: str | None = None
    display: str | None = None
    # the rule's fix needs a name the tool cannot invent (--name/--fix-name):
    # the LSP marks its code action `needsName` so a client can prompt, and
    # the CLI refuses a missing/invalid name with an explicit message
    fix_name_required: bool = False


# The config group a rule belongs to (RULE_GROUPS / rule_groups — the
# gate's and the LSP's `group:` suppression expansion). Derived from the
# display group: RULES.md sections are documentation, the four config
# groups are the suppression surface; advice rules suppress with style,
# graph rules with architecture.
_CONFIG_GROUP = {
    "architecture": "architecture",
    "style": "style",
    "test-discipline": "test-discipline",
    "suppression": "suppression",
    "advice": "style",
    "graph": "architecture",
    "cross-cutting": "style",
}


class RuleCatalog:
    """The collection of rules — the derived views the rest of the tool
    consumes (groups, families, display buckets)."""

    def __init__(self, rules: list[Rule]) -> None:
        self.rules: list[Rule] = rules

    def kinds(self) -> list[str]:
        return [r.kind for r in self.rules]

    def by_kind(self, kind: str) -> Rule | None:
        return next((r for r in self.rules if r.kind == kind), None)

    def config_group_of(self, kind: str) -> str:
        rule = self.by_kind(kind)
        if rule is None:
            return "style"  # unknown kinds suppress with the catch-all group
        return _CONFIG_GROUP[rule.display_group]

    # the derived-view map is the catalog's output wire format — one
    # consumer each, a class is ceremony
    # lucidlint: ignore record-shape the derived-view map is the catalog's output wire format
    def groups(self) -> dict[str, set[str]]:
        """config group -> kinds — the RULE_GROUPS map (gate + config.rs
        mirror both derive from here)."""
        out: dict[str, set[str]] = {}
        for r in self.rules:
            out.setdefault(self.config_group_of(r.kind), set()).add(r.kind)
        return out

    # the derived-view map is the catalog's output wire format — one
    # consumer each, a class is ceremony
    # lucidlint: ignore record-shape the derived-view map is the catalog's output wire format
    def families(self) -> dict[str, list[str]]:
        """display bucket -> variant kinds — FAMILY_VARIANTS. A family is a
        display value that is not a kind and not "standard"; every rule with
        that display is a variant of it."""
        kinds = set(self.kinds())
        fam: dict[str, list[str]] = {}
        for r in self.rules:
            if r.display and r.display != "standard" and r.display not in kinds:
                fam.setdefault(r.display, []).append(r.kind)
        return fam



    def standard_kinds(self) -> list[str]:
        return [r.kind for r in self.rules if r.display == "standard"]

    def final_kind(self, kind: str) -> str:
        """The display bucket: the family/own bucket from the catalog, or
        the "standard" catch-all for unknown kinds."""
        rule = self.by_kind(kind)
        if rule is not None:
            return rule.display or rule.kind
        return "standard"

    def display_name_of(self, kind: str) -> str:
        rule = self.by_kind(kind)
        if rule is not None:
            return rule.display_name or rule.kind
        return kind


# (kind, severity, display_group, languages, description[, display_name][, display])
CATALOG = RuleCatalog([
    # ---- architecture
    Rule("complexity", "fail", "architecture", "Both",
         "Cyclomatic complexity ≥ 15 (radon-equivalent rules: `if`/`elif` count, "
         "`match` arms minus wildcard, `&&`/`||`, ternary, loops, `assert!`, "
         "closures +0 walked) — Extract Function: `lucidlint fix --kind "
         "extract-method --file <F> --line <L>` previews the best self-contained "
         "seam (placeholder name — the extracted function is private by "
         "construction, so the fix underscores it); apply with `--name <N>` "
         "(the name IS the commitment — no `--confirm`).",
         fix_name_required=True),
    Rule("long-param-list", "fail", "architecture", "Both",
         "A function with > 5 parameters (receiver/`self` excluded) — introduce "
         "a parameter object.",
         fix_name_required=True),
    Rule("large-function", "fail", "architecture", "Both",
         "Function spans ≥ 120 lines — split it: one rule per function."),
    Rule("closures", "fail", "architecture", "Both",
         "A function defining ≥2 inner functions/closures (≥15 CC *or* ≥60 line "
         "span) — the nested structure is a class waiting to be extracted.",
         display_name="closures → latent-class", display="latent-class"),
    Rule("partition", "fail", "architecture", "Python",
         "The field-partition variant of latent-class: free functions partition "
         "a struct's fields (each touches a disjoint subset) — the fields and "
         "their functions belong together as a class.",
         display_name="partition → latent-class", display="latent-class"),
    Rule("strewing", "fail", "architecture", "Both",
         "≥3 free functions sharing the same leading parameter — they share "
         "data, they're a class.",
         display_name="strewing → latent-class", display="latent-class"),
    Rule("misplaced-method", "fail", "architecture", "Python",
         "A module-level function called from a method with `self.<attr>` "
         "arguments matching every parameter — the class already holds the "
         "data, so the function is that class's method in exile; move it "
         "onto the class.",
         display_name="misplaced-method → latent-class", display="latent-class"),
    Rule("assembly-class", "fail", "architecture", "Python",
         "A function assembles >=3 structures by threading the same data "
         "through module-level functions whose outputs feed each other's "
         "inputs — a class in waiting: the threaded state belongs on an "
         "object, the module functions are its methods.",
         display_name="assembly-class → latent-class", display="latent-class"),
    Rule("tuple-record", "fail", "architecture", "Python",
         "A dict whose values are same-arity tuples read with constant "
         "integer indexes — an anonymous record; make it a class (the "
         "record's fields are the tuple positions).",
         display_name="tuple-record → latent-class", display="latent-class",
         fix_name_required=True),
    Rule("data-clump", "fail", "architecture", "Python",
         ">=3 module functions sharing the same parameter pair — the pair "
         "travels together, so it is a data clump; introduce a parameter "
         "object that holds it.",
         display_name="data-clump → latent-class", display="latent-class"),
    Rule("feature-envy", "fail", "architecture", "Python",
         "A method reads another object's fields more than its own state — "
         "the logic belongs on that object (feature envy); move the "
         "computation onto the envied class as a method.",
         display_name="feature-envy → latent-class", display="latent-class",
         fix_name_required=True),
    Rule("undeclared-attribute", "fail", "architecture", "Python",
         "A class must DECLARE its members — annotated in the class body, in "
         "__slots__, or in __init__ — not assign them quietly in member "
         "functions. A plain `self.x = ...` in __init__ or any member "
         "assigned outside the constructor without a declaration is a "
         "finding: declare it.",
         display_name="undeclared-attribute", display=None),
    Rule("god-class", "warn", "architecture", "Python",
         "A class with >=20 methods, or >=12 methods over >=250 lines — a "
         "large class. A review signal, not a split order: split only where "
         "the partition rule finds field-disjoint method groups.",
         display_name="god-class → latent-class", display="latent-class"),
    Rule("duplicate-field", "fail", "architecture", "Python",
         "A class and a class it CONTAINS both hold the same >=2 fields — "
         "duplicated domain state across a containment edge; one source of "
         "truth should own it.",
         display_name="duplicate-field → latent-class", display="latent-class"),
    Rule("module-cohesion", "fail", "architecture", "Graph",
         "A file whose nodes split across ≥2 graph communities (each ≥2 nodes) "
         "holds several sub-domains — split the module at the domain seams."),
    Rule("record-shape", "fail", "architecture", "Both",
         "A function takes a struct/class with ≥5 fields and no methods — the "
         "struct's rules belong as methods on it."),
    Rule("detached-method", "warn", "architecture", "Both",
         "A method that never touches its receiver — a classmethod should "
         "always use `cls`; a plain method should use `self` or move out — it "
         "doesn't use instance state; make it a `@staticmethod`/associated fn "
         "or move it out of the class."),
    Rule("duplicate", "warn", "architecture", "Both",
         "Dice similarity ≥ 0.9 (structural skeleton bigrams) — copy-paste; "
         "extract the shared logic.",
         display="standard"),
    Rule("layer-mix", "fail", "architecture", "Graph",
         "A file calls into multiple architectural layers (determined via the "
         "code-review-graph contract) — files belong in one layer."),
    Rule("folder-mix", "fail", "architecture", "Graph",
         "Files in a directory are split across graph communities — they belong "
         "together."),
    # ---- style
    Rule("magic-number", "warn", "style", "Both",
         "Numeric literal (outside 0/1/2) used as an operand — name it as a "
         "constant.",
         fix_name_required=True),
    Rule("debug-artifact", "fail", "style", "Both",
         "`dbg!()` / `.unwrap()` / `.expect()` in production Rust; "
         "`breakpoint()` in production Python — debugging left in."),
    Rule("noop-statement", "fail", "style", "Both",
         "Expression statement that discards its value (`x;`, `a + b;`) — dead "
         "statement."),
    Rule("unreachable", "fail", "style", "Both",
         "Statement after an unconditional `return`/`break`/`continue`/`panic!` "
         "— dead code is deleted."),
    Rule("vague-name", "fail", "style", "Both",
         "Type ending in Manager, Handler, Store, Repository, Controller, Utils, "
         "or Info with significant size/methods — the domain concept should "
         "name it.",
         fix_name_required=True),
    Rule("class-module", "fail", "style", "Python",
         "A Python module holding exactly one class whose name doesn't match "
         "the filename — rename the file to match.",
         display="standard"),
    Rule("builtin-shadow", "fail", "style", "Python",
         "A variable/parameter that shadows a Python builtin (`list`, `dict`, "
         "`str`, `id`...).",
         display="standard"),
    Rule("broad-except", "warn", "style", "Python",
         "Bare `except:` — catch specific exceptions.",
         display="standard"),
    Rule("boolean-arg", "fail", "style", "Both",
         "A boolean literal passed as a call argument (`connect(host, True)`) — "
         "name the flag at the call site."),
    Rule("positional-literals", "warn", "style", "Both",
         "A call passing ≥2 literals of the same kind positionally "
         "(`set_limits(10, 20)`) — a swapped argument is a silent bug; use "
         "keyword arguments."),
    Rule("swallow", "fail", "style", "Both",
         "A catch that neither re-raises nor exits with control flow (no "
         "return/break/continue); in Rust, a `Result`/`Option` discarded with "
         "`let _ =` — the error vanishes, re-raise or handle it."),
    Rule("inline-import", "fail", "style", "Python",
         "`import` inside a function body (Python) — imports belong at module "
         "top.",
         display="standard"),
    Rule("private-import", "fail", "style", "Both",
         "Importing an underscore-prefixed symbol from another module.",
         display="standard"),
    Rule("global-state", "fail", "style", "Both",
         "Module-level mutable container mutated inside a function — put state "
         "in a class.",
         display="standard"),
    Rule("unused", "warn", "style", "Python",
         "A function defined in production code that's never referenced "
         "anywhere in the repo (same-file references count — Python only).",
         display="standard"),
    Rule("duplicate-def", "fail", "style", "Both",
         "A module-scope def/class/import that shadows an earlier module-scope "
         "binding of the same name — the later definition wins legally, but it "
         "is a shadowing hazard (dispatch or edit mistake); rename one."),
    Rule("restating-docstring", "warn", "style", "Both",
         "A docstring whose content words all appear in the body's own tokens "
         "— it restates the code; name the concept instead."),
    Rule("duplicate-block", "warn", "style", "Both",
         "An identical statement block (≥3 statements) appearing twice in one "
         "function — duplicated work (an edit mistake?); delete the second "
         "copy."),
    Rule("import-cycle", "fail", "style", "Both",
         "Circular imports — restructure modules.",
         display="standard"),
    Rule("docs-link", "fail", "style", "Both",
         "An internal MD link or backticked path does not resolve to an "
         "existing file.",
         display="docs"),
    Rule("docs-undiscoverable", "fail", "style", "Both",
         "A doc file is not reachable from `AGENTS.md` (the repo's doc index) "
         "via the link graph.",
         display="docs"),
    # ---- test discipline
    Rule("monkeypatch", "fail", "test-discipline", "Python",
         "`monkeypatch`/`unittest.mock.patch` — prefer dependency injection.",
         display="standard"),
    Rule("skipif", "fail", "test-discipline", "Both",
         "`@pytest.mark.skipif` on environment presence (`os.environ`, "
         "`sys.platform`, etc.), a bare `@pytest.mark.skip`, or `#[test] "
         "#[ignore]` — a skipped test rots; fake the dependency instead."),
    Rule("fakefs", "fail", "test-discipline", "Both",
         "Real filesystem I/O (`open`, `pathlib.Path`) in a test without "
         "`pyfakefs` — tests fake the filesystem.",
         display="standard"),
    Rule("no-assert-test", "fail", "test-discipline", "Both",
         "A test function with no assertion anywhere in its body — it can never "
         "fail."),
    # ---- suppression discipline
    Rule("suppression", "fail", "suppression", "Both",
         "`lucidlint: ignore <signal>` with no explanation — every exemption "
         "needs a why.",
         display="standard"),
    Rule("type-ignore", "fail", "suppression", "Python",
         "`# type: ignore` with no comment — a suppression is itself a finding; "
         "explain why the checker is wrong.",
         display="standard"),
    Rule("allow-reason", "fail", "suppression", "Rust",
         "`#[allow(...)]` / `#[expect(...)]` with no reason comment on the line "
         "or the line above.",
         display="standard"),
    Rule("noqa", "fail", "suppression", "Python",
         "`# noqa` / `# pragma: no cover` with no explanation — a suppression "
         "is itself a finding."),
    Rule("stale-suppression", "fail", "suppression", "Both",
         "A `lucidlint: ignore` / `ignore-file` that no longer suppresses "
         "anything — remove it."),
    # ---- refactoring advice (all warn — detection-only)
    Rule("guard-clauses", "warn", "advice", "Python",
         "≥3 levels of if-in-if (\"arrow code\") — Replace Nested Conditional "
         "with Guard Clauses: invert to early returns."),
    Rule("latent-visitor", "warn", "advice", "Both",
         "≥2 operations dispatching over the same element family "
         "(`isinstance`/`type()` chains) — Replace Conditional with Visitor: "
         "elements accept a visitor with `visit_<Type>` methods. Chains this "
         "rule claims are exempt from conditional-polymorphism — one ruling per "
         "chain."),
    Rule("conditional-polymorphism", "warn", "advice", "Python",
         "An if/elif chain of ≥4 arms dispatching on the same value — Replace "
         "Conditional with Polymorphism."),
    Rule("special-case", "warn", "advice", "Python",
         "≥3 repeated `None`/empty checks on one name — Introduce Special "
         "Case."),
    Rule("middle-man", "warn", "advice", "Python",
         "A method that only forwards (`return self.x.y(...)`) — Remove Middle "
         "Man."),
    Rule("unused-setter", "warn", "advice", "Python",
         "A `set_*` method or property setter never referenced — Remove Setting "
         "Method."),
    Rule("loop-pipeline", "warn", "advice", "Python",
         "A loop whose body is only a collection mutation — Replace Loop with "
         "Pipeline: use a comprehension."),
    # ---- graph-based (require code-review-graph)
    Rule("hub-file", "fail", "graph", "Graph",
         "A file with ≥150 incoming or outgoing call/import edges — central "
         "module that may need splitting."),
    Rule("high-risk", "fail", "graph", "Graph",
         "A function with >10 callers, no test coverage, and/or a "
         "security-related name (`auth`, `login`, `token`, `sql`...)."),
    Rule("hotspot", "fail", "graph", "Graph",
         "A file in the top N% by churn with a function at ≥15 CC — volatile "
         "code that needs refactoring."),
    Rule("churn-untested", "fail", "graph", "Graph",
         "A file in the top N% by churn with no test coverage — volatile and "
         "unverified."),
    Rule("over-abstraction", "fail", "graph", "Graph",
         "An abstract base class (Python ABC) with exactly one concrete "
         "subclass — the abstraction doesn't earn its keep.",
         display="standard"),
])
