// GENERATED by scripts/gen-rules.py (`make rules`) — DO NOT EDIT.
//
// The single source of truth is rule_metadata.py's RuleCatalog:
// adding a rule there and running `make rules` regenerates this
// module, RULES.md, and the Python RULE_GROUPS map. The drift gate
// (`make rules --check` / test_rules_md_is_generated) fails when
// this file is stale — hand-editing it is a second registration
// point and the one thing this module exists to forbid.

/// Every kind the catalog registers — the scanner's contract.
pub const FAMILY_KINDS: &[&str] = &[
    "complexity",
    "long-param-list",
    "large-function",
    "closures",
    "partition",
    "strewing",
    "misplaced-method",
    "assembly-class",
    "tuple-record",
    "data-clump",
    "feature-envy",
    "undeclared-attribute",
    "god-class",
    "duplicate-field",
    "module-cohesion",
    "record-shape",
    "detached-method",
    "duplicate",
    "layer-mix",
    "folder-mix",
    "magic-number",
    "debug-artifact",
    "noop-statement",
    "unreachable",
    "vague-name",
    "class-module",
    "builtin-shadow",
    "broad-except",
    "boolean-arg",
    "positional-literals",
    "swallow",
    "inline-import",
    "private-import",
    "global-state",
    "unused",
    "duplicate-def",
    "restating-docstring",
    "duplicate-block",
    "import-cycle",
    "docs-link",
    "docs-undiscoverable",
    "monkeypatch",
    "skipif",
    "fakefs",
    "no-assert-test",
    "suppression",
    "type-ignore",
    "allow-reason",
    "noqa",
    "stale-suppression",
    "guard-clauses",
    "latent-visitor",
    "conditional-polymorphism",
    "special-case",
    "middle-man",
    "unused-setter",
    "loop-pipeline",
    "hub-file",
    "high-risk",
    "hotspot",
    "churn-untested",
    "over-abstraction",
];

/// Kinds that deliberately collapse to the "standard" display
/// bucket — their messages carry the rule; a named `final_kind`
/// bucket is optional for them.
pub const STANDARD_KINDS: &[&str] = &[
    "duplicate",
    "class-module",
    "builtin-shadow",
    "broad-except",
    "inline-import",
    "private-import",
    "global-state",
    "unused",
    "import-cycle",
    "monkeypatch",
    "fakefs",
    "suppression",
    "type-ignore",
    "allow-reason",
    "over-abstraction",
];

/// Family -> variant kinds, for family suppressions (`ignore
/// latent-class <why>` covers every variant). Derived from the
/// catalog's `display` buckets — a variant missing here is a
/// registration drift, not a judgment call (review-log B6).
pub const FAMILY_VARIANTS: &[(&str, &[&str])] = &[
    (
        "latent-class",
        &[
            "closures",
            "partition",
            "strewing",
            "misplaced-method",
            "assembly-class",
            "data-clump",
            "feature-envy",
            "god-class",
            "duplicate-field",
        ],
    ),
    ("docs", &["docs-link", "docs-undiscoverable"]),
];

/// kind -> display bucket — the lookup table final_kind scans.
/// A match of 50+ arms would be a complexity finding; data
/// stays flat (a linear scan over the entries is nothing).
pub const DISPLAY_BUCKETS: &[(&str, &str)] = &[
    ("complexity", "complexity"),
    ("long-param-list", "long-param-list"),
    ("large-function", "large-function"),
    ("closures", "latent-class"),
    ("partition", "latent-class"),
    ("strewing", "latent-class"),
    ("misplaced-method", "latent-class"),
    ("assembly-class", "latent-class"),
    ("tuple-record", "record-shape"),
    ("data-clump", "latent-class"),
    ("feature-envy", "latent-class"),
    ("undeclared-attribute", "undeclared-attribute"),
    ("god-class", "latent-class"),
    ("duplicate-field", "latent-class"),
    ("module-cohesion", "module-cohesion"),
    ("record-shape", "record-shape"),
    ("detached-method", "detached-method"),
    ("duplicate", "standard"),
    ("layer-mix", "layer-mix"),
    ("folder-mix", "folder-mix"),
    ("magic-number", "magic-number"),
    ("debug-artifact", "debug-artifact"),
    ("noop-statement", "noop-statement"),
    ("unreachable", "unreachable"),
    ("vague-name", "vague-name"),
    ("class-module", "standard"),
    ("builtin-shadow", "standard"),
    ("broad-except", "standard"),
    ("boolean-arg", "boolean-arg"),
    ("positional-literals", "positional-literals"),
    ("swallow", "swallow"),
    ("inline-import", "standard"),
    ("private-import", "standard"),
    ("global-state", "standard"),
    ("unused", "standard"),
    ("duplicate-def", "duplicate-def"),
    ("restating-docstring", "restating-docstring"),
    ("duplicate-block", "duplicate-block"),
    ("import-cycle", "standard"),
    ("docs-link", "docs"),
    ("docs-undiscoverable", "docs"),
    ("monkeypatch", "standard"),
    ("skipif", "skipif"),
    ("fakefs", "standard"),
    ("no-assert-test", "no-assert-test"),
    ("suppression", "standard"),
    ("type-ignore", "standard"),
    ("allow-reason", "standard"),
    ("noqa", "noqa"),
    ("stale-suppression", "stale-suppression"),
    ("guard-clauses", "guard-clauses"),
    ("latent-visitor", "latent-visitor"),
    ("conditional-polymorphism", "conditional-polymorphism"),
    ("special-case", "special-case"),
    ("middle-man", "middle-man"),
    ("unused-setter", "unused-setter"),
    ("loop-pipeline", "loop-pipeline"),
    ("hub-file", "hub-file"),
    ("high-risk", "high-risk"),
    ("hotspot", "hotspot"),
    ("churn-untested", "churn-untested"),
    ("over-abstraction", "standard"),
];

/// The display bucket for a finding kind — `final_kind` output.
pub fn final_kind(kind: &str) -> &'static str {
    for (k, bucket) in DISPLAY_BUCKETS {
        if *k == kind {
            return bucket;
        }
    }
    "standard"
}

/// The config `group:` expansion — the LSP's mirror of the
/// gate's RULE_GROUPS (both derived from the same catalog).
pub fn rule_groups() -> &'static [(&'static str, &'static [&'static str])] {
    &[
        (
            "architecture",
            &[
                "assembly-class",
                "churn-untested",
                "closures",
                "complexity",
                "data-clump",
                "detached-method",
                "duplicate",
                "duplicate-field",
                "feature-envy",
                "folder-mix",
                "god-class",
                "high-risk",
                "hotspot",
                "hub-file",
                "large-function",
                "layer-mix",
                "long-param-list",
                "misplaced-method",
                "module-cohesion",
                "over-abstraction",
                "partition",
                "record-shape",
                "strewing",
                "tuple-record",
                "undeclared-attribute",
            ],
        ),
        (
            "style",
            &[
                "boolean-arg",
                "broad-except",
                "builtin-shadow",
                "class-module",
                "conditional-polymorphism",
                "debug-artifact",
                "docs-link",
                "docs-undiscoverable",
                "duplicate-block",
                "duplicate-def",
                "global-state",
                "guard-clauses",
                "import-cycle",
                "inline-import",
                "latent-visitor",
                "loop-pipeline",
                "magic-number",
                "middle-man",
                "noop-statement",
                "positional-literals",
                "private-import",
                "restating-docstring",
                "special-case",
                "swallow",
                "unreachable",
                "unused",
                "unused-setter",
                "vague-name",
            ],
        ),
        (
            "test-discipline",
            &["fakefs", "monkeypatch", "no-assert-test", "skipif"],
        ),
        (
            "suppression",
            &[
                "allow-reason",
                "noqa",
                "stale-suppression",
                "suppression",
                "type-ignore",
            ],
        ),
    ]
}
